### ISSUE TITLE
Dodati continue-on-error u pre_check

### ISSUE THREAD

**Issue by kozicpetar** [mint-hosting/nginx-module-brotli#3]
Kako github actions ne bi prikazivao fail status ukoliko uslov nije ispunjen za buildovanje modula, potrebno je dodati continue-on-error.

```
pre_check:
    name: Pre-build checks
    runs-on: ubuntu-latest
    continue-on-error: true
```
